[package]
name = "lcl-report-parser"
version = "0.1.0"
authors = ["Ivaylo Petrov <ivajloip@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
regex = "1"
yaml-rust = "0.4"
